@extends('layouts.app')

@section('content')
<div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
    <h1 class="text-xl font-semibold text-slate-800 dark:text-white">Backups &amp; Recovery</h1>
    <form method="POST" action="{{ route('backups.store') }}" onsubmit="return confirm('Start manual backup?')" class="flex justify-end">
        @csrf
        <button class="inline-flex items-center rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white transition hover:bg-slate-800 dark:bg-slate-700 dark:hover:bg-slate-600">Run backup</button>
    </form>
</div>
@if($errors->has('restore'))
    <div class="mt-4 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700 dark:border-rose-800/50 dark:bg-rose-900/20 dark:text-rose-200">
        {{ $errors->first('restore') }}
    </div>
@endif
<div class="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-800/50">
    <table class="w-full text-sm">
        <thead class="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500 dark:bg-slate-900/50 dark:text-slate-400">
            <tr>
                <th class="px-4 py-3">File</th>
                <th class="px-4 py-3">Status</th>
                <th class="px-4 py-3">Operator</th>
                <th class="px-4 py-3">Created</th>
                <th class="px-4 py-3"></th>
            </tr>
        </thead>
        <tbody>
            @foreach($backups as $backup)
                <tr class="border-t border-slate-100 dark:border-slate-700">
                    <td class="px-4 py-3 font-mono text-xs dark:text-slate-300">{{ $backup->file_path ?: 'pending' }}</td>
                    <td class="px-4 py-3">
                        <span class="rounded-full px-3 py-1 text-xs font-semibold {{ $backup->status === 'completed' ? 'bg-emerald-100 text-emerald-700' : ($backup->status === 'failed' ? 'bg-rose-100 text-rose-700' : 'bg-amber-100 text-amber-700') }}">{{ ucfirst($backup->status) }}</span>
                    </td>
                    <td class="px-4 py-3 dark:text-slate-200">{{ $backup->operator?->name ?? '—' }}</td>
                    <td class="px-4 py-3 dark:text-slate-200">{{ $backup->created_at->format('M d, Y H:i') }}</td>
                    <td class="px-4 py-3">
                        @if($backup->status === 'completed')
                            <div class="flex items-center justify-end gap-3">
                                <a href="{{ route('backups.download', $backup) }}" class="text-sky-600 hover:text-sky-700 dark:text-sky-400 dark:hover:text-sky-300">Download</a>
                                <form method="POST" action="{{ route('backups.restore-job', $backup) }}" class="inline" onsubmit="return confirm('Restore the system using this backup? This will overwrite current data.');">
                                    @csrf
                                    <button type="submit" class="text-emerald-600 hover:text-emerald-700 dark:text-emerald-400 dark:hover:text-emerald-300">Restore</button>
                                </form>
                            </div>
                        @endif
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
</div>
<div class="mt-4">
    {{ $backups->links() }}
</div>
<div class="mt-8 rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-800/50">
    <h2 class="text-base font-semibold text-slate-800 dark:text-white">Restore from backup file</h2>
    <p class="mt-1 text-sm text-slate-500 dark:text-slate-400">Upload a backup JSON generated by this system to overwrite the current data.</p>
    <form method="POST" action="{{ route('backups.restore-upload') }}" enctype="multipart/form-data" class="mt-4 space-y-3">
        @csrf
        <div>
            <label class="text-sm font-medium text-slate-700 dark:text-slate-200" for="backup_file">Backup file</label>
            <input type="file" name="backup_file" id="backup_file" accept="application/json,.json" class="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-800 focus:border-slate-500 focus:outline-none focus:ring-4 focus:ring-slate-200 dark:border-slate-700 dark:bg-slate-900 dark:text-white dark:focus:border-slate-500 dark:focus:ring-slate-700" required>
            @error('backup_file')
                <p class="mt-1 text-sm text-rose-600 dark:text-rose-400">{{ $message }}</p>
            @enderror
        </div>
        <button type="submit" class="inline-flex items-center rounded-lg bg-emerald-600 px-4 py-2 text-sm font-semibold text-white transition hover:bg-emerald-500">Restore backup</button>
    </form>
</div>
@endsection
